networks:
  earth_orbit_network:
    ipam:
      config:
      - subnet: 172.21.0.0/16
  earth_surface_network:
    ipam:
      config:
      - subnet: 172.20.0.0/16
  moon_orbit_network:
    ipam:
      config:
      - subnet: 172.23.0.0/16
  moon_surface_network:
    ipam:
      config:
      - subnet: 172.22.0.0/16
services:
  earth_orbit_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: earth_orbit_1
    networks:
      earth_orbit_network:
        ipv4_address: 172.21.1.3
      earth_surface_network:
        ipv4_address: 172.20.1.3
      moon_orbit_network:
        ipv4_address: 172.23.1.3
      moon_surface_network:
        ipv4_address: 172.22.1.3
    ports:
    - 50003:5001
    privileged: true
    tty: true
  earth_surface_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: earth_surface_1
    networks:
      earth_orbit_network:
        ipv4_address: 172.21.1.1
      earth_surface_network:
        ipv4_address: 172.20.1.1
      moon_orbit_network:
        ipv4_address: 172.23.1.1
      moon_surface_network:
        ipv4_address: 172.22.1.1
    ports:
    - 50001:5001
    privileged: true
    tty: true
  earth_surface_2:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: earth_surface_2
    networks:
      earth_orbit_network:
        ipv4_address: 172.21.1.2
      earth_surface_network:
        ipv4_address: 172.20.1.2
      moon_orbit_network:
        ipv4_address: 172.23.1.2
      moon_surface_network:
        ipv4_address: 172.22.1.2
    ports:
    - 50002:5001
    privileged: true
    tty: true
  moon_orbit_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: moon_orbit_1
    networks:
      earth_orbit_network:
        ipv4_address: 172.21.1.4
      earth_surface_network:
        ipv4_address: 172.20.1.4
      moon_orbit_network:
        ipv4_address: 172.23.1.4
      moon_surface_network:
        ipv4_address: 172.22.1.4
    ports:
    - 50004:5001
    privileged: true
    tty: true
  moon_surface_1:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: moon_surface_1
    networks:
      earth_orbit_network:
        ipv4_address: 172.21.1.5
      earth_surface_network:
        ipv4_address: 172.20.1.5
      moon_orbit_network:
        ipv4_address: 172.23.1.5
      moon_surface_network:
        ipv4_address: 172.22.1.5
    ports:
    - 50005:5001
    privileged: true
    tty: true
  moon_surface_2:
    build:
      context: ./
      dockerfile: ./input/Dockerfile
    container_name: moon_surface_2
    networks:
      earth_orbit_network:
        ipv4_address: 172.21.1.6
      earth_surface_network:
        ipv4_address: 172.20.1.6
      moon_orbit_network:
        ipv4_address: 172.23.1.6
      moon_surface_network:
        ipv4_address: 172.22.1.6
    ports:
    - 50006:5001
    privileged: true
    tty: true
version: '3.8'
