networks:
  earth_orbit1_earth_surface1_network:
    ipam:
      config:
      - subnet: 172.0.2.0/24
  earth_orbit1_earth_surface2_network:
    ipam:
      config:
      - subnet: 172.0.7.0/24
  earth_orbit1_moon_orbit1_network:
    ipam:
      config:
      - subnet: 172.0.12.0/24
  earth_orbit1_moon_orbit2_network:
    ipam:
      config:
      - subnet: 172.0.13.0/24
  earth_orbit1_moon_surface1_network:
    ipam:
      config:
      - subnet: 172.0.14.0/24
  earth_orbit1_moon_surface2_network:
    ipam:
      config:
      - subnet: 172.0.15.0/24
  earth_surface1_earth_surface2_network:
    ipam:
      config:
      - subnet: 172.0.1.0/24
  earth_surface1_moon_orbit1_network:
    ipam:
      config:
      - subnet: 172.0.3.0/24
  earth_surface1_moon_orbit2_network:
    ipam:
      config:
      - subnet: 172.0.4.0/24
  earth_surface1_moon_surface1_network:
    ipam:
      config:
      - subnet: 172.0.5.0/24
  earth_surface1_moon_surface2_network:
    ipam:
      config:
      - subnet: 172.0.6.0/24
  earth_surface2_moon_orbit1_network:
    ipam:
      config:
      - subnet: 172.0.8.0/24
  earth_surface2_moon_orbit2_network:
    ipam:
      config:
      - subnet: 172.0.9.0/24
  earth_surface2_moon_surface1_network:
    ipam:
      config:
      - subnet: 172.0.10.0/24
  earth_surface2_moon_surface2_network:
    ipam:
      config:
      - subnet: 172.0.11.0/24
  moon_orbit1_moon_orbit2_network:
    ipam:
      config:
      - subnet: 172.0.16.0/24
  moon_orbit1_moon_surface1_network:
    ipam:
      config:
      - subnet: 172.0.17.0/24
  moon_orbit1_moon_surface2_network:
    ipam:
      config:
      - subnet: 172.0.18.0/24
  moon_orbit2_moon_surface1_network:
    ipam:
      config:
      - subnet: 172.0.19.0/24
  moon_orbit2_moon_surface2_network:
    ipam:
      config:
      - subnet: 172.0.20.0/24
  moon_surface1_moon_surface2_network:
    ipam:
      config:
      - subnet: 172.0.21.0/24
services:
  earth_orbit1:
    build:
      context: .
      dockerfile: ./input/Dockerfile
    container_name: earth_orbit1
    networks:
      earth_orbit1_earth_surface1_network:
        ipv4_address: 172.0.2.3
      earth_orbit1_earth_surface2_network:
        ipv4_address: 172.0.7.3
      earth_orbit1_moon_orbit1_network:
        ipv4_address: 172.0.12.2
      earth_orbit1_moon_orbit2_network:
        ipv4_address: 172.0.13.2
      earth_orbit1_moon_surface1_network:
        ipv4_address: 172.0.14.2
      earth_orbit1_moon_surface2_network:
        ipv4_address: 172.0.15.2
    ports:
    - 50002:5001
    privileged: true
    tty: true
  earth_surface1:
    build:
      context: .
      dockerfile: ./input/Dockerfile
    container_name: earth_surface1
    networks:
      earth_orbit1_earth_surface1_network:
        ipv4_address: 172.0.2.2
      earth_surface1_earth_surface2_network:
        ipv4_address: 172.0.1.2
      earth_surface1_moon_orbit1_network:
        ipv4_address: 172.0.3.2
      earth_surface1_moon_orbit2_network:
        ipv4_address: 172.0.4.2
      earth_surface1_moon_surface1_network:
        ipv4_address: 172.0.5.2
      earth_surface1_moon_surface2_network:
        ipv4_address: 172.0.6.2
    ports:
    - 50000:5001
    privileged: true
    tty: true
  earth_surface2:
    build:
      context: .
      dockerfile: ./input/Dockerfile
    container_name: earth_surface2
    networks:
      earth_orbit1_earth_surface2_network:
        ipv4_address: 172.0.7.2
      earth_surface1_earth_surface2_network:
        ipv4_address: 172.0.1.3
      earth_surface2_moon_orbit1_network:
        ipv4_address: 172.0.8.2
      earth_surface2_moon_orbit2_network:
        ipv4_address: 172.0.9.2
      earth_surface2_moon_surface1_network:
        ipv4_address: 172.0.10.2
      earth_surface2_moon_surface2_network:
        ipv4_address: 172.0.11.2
    ports:
    - 50001:5001
    privileged: true
    tty: true
  moon_orbit1:
    build:
      context: .
      dockerfile: ./input/Dockerfile
    container_name: moon_orbit1
    networks:
      earth_orbit1_moon_orbit1_network:
        ipv4_address: 172.0.12.3
      earth_surface1_moon_orbit1_network:
        ipv4_address: 172.0.3.3
      earth_surface2_moon_orbit1_network:
        ipv4_address: 172.0.8.3
      moon_orbit1_moon_orbit2_network:
        ipv4_address: 172.0.16.2
      moon_orbit1_moon_surface1_network:
        ipv4_address: 172.0.17.2
      moon_orbit1_moon_surface2_network:
        ipv4_address: 172.0.18.2
    ports:
    - 50003:5001
    privileged: true
    tty: true
  moon_orbit2:
    build:
      context: .
      dockerfile: ./input/Dockerfile
    container_name: moon_orbit2
    networks:
      earth_orbit1_moon_orbit2_network:
        ipv4_address: 172.0.13.3
      earth_surface1_moon_orbit2_network:
        ipv4_address: 172.0.4.3
      earth_surface2_moon_orbit2_network:
        ipv4_address: 172.0.9.3
      moon_orbit1_moon_orbit2_network:
        ipv4_address: 172.0.16.3
      moon_orbit2_moon_surface1_network:
        ipv4_address: 172.0.19.2
      moon_orbit2_moon_surface2_network:
        ipv4_address: 172.0.20.2
    ports:
    - 50004:5001
    privileged: true
    tty: true
  moon_surface1:
    build:
      context: .
      dockerfile: ./input/Dockerfile
    container_name: moon_surface1
    networks:
      earth_orbit1_moon_surface1_network:
        ipv4_address: 172.0.14.3
      earth_surface1_moon_surface1_network:
        ipv4_address: 172.0.5.3
      earth_surface2_moon_surface1_network:
        ipv4_address: 172.0.10.3
      moon_orbit1_moon_surface1_network:
        ipv4_address: 172.0.17.3
      moon_orbit2_moon_surface1_network:
        ipv4_address: 172.0.19.3
      moon_surface1_moon_surface2_network:
        ipv4_address: 172.0.21.2
    ports:
    - 50005:5001
    privileged: true
    tty: true
  moon_surface2:
    build:
      context: .
      dockerfile: ./input/Dockerfile
    container_name: moon_surface2
    networks:
      earth_orbit1_moon_surface2_network:
        ipv4_address: 172.0.15.3
      earth_surface1_moon_surface2_network:
        ipv4_address: 172.0.6.3
      earth_surface2_moon_surface2_network:
        ipv4_address: 172.0.11.3
      moon_orbit1_moon_surface2_network:
        ipv4_address: 172.0.18.3
      moon_orbit2_moon_surface2_network:
        ipv4_address: 172.0.20.3
      moon_surface1_moon_surface2_network:
        ipv4_address: 172.0.21.3
    ports:
    - 50006:5001
    privileged: true
    tty: true
version: '3.7'
