version: '5.1'
services:
  earth_surface_1:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile
    container_name: "earth_surface_1"
    networks:
      fixed_compose_network:
        ipv4_address: 172.20.1.1
    ports:
    - 50001:5001/tcp
    - 50001:5001/udp
    tty: true

  earth_orbit_1:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile
    container_name: "earth_orbit_1"
    networks:
      fixed_compose_network:
        ipv4_address: 172.20.2.1
    ports:
    - 50002:5001/tcp
    - 50002:5001/udp
    tty: true

  moon_surface_1:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile
    container_name: "moon_surface_1"
    networks:
      fixed_compose_network:
        ipv4_address: 172.20.3.1
    ports:
    - 50003:5001/tcp
    - 50003:5001/udp
    tty: true

  moon_orbit_1:
    build:
      context: ./
      dockerfile: dockerfile/Dockerfile
    container_name: "moon_orbit_1"
    networks:
      fixed_compose_network:
        ipv4_address: 172.20.4.1
    ports:
    - 50004:5001/tcp
    - 50004:5001/udp
    tty: true

networks:
  fixed_compose_network:
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16
