networks:
  test_net:
    ipam:
      config:
      - subnet: 192.168.10.0/24
services:
  earth_orbit_1:
    build:
      context: .
      dockerfile: ./container-maker/Dockerfile
    container_name: earth_orbit_1
    networks:
      test_net:
        ipv4_address: 192.168.10.150
    volumes:
      - ./ion-dtn-test/host149.rc:/dtn/host150.rc
    ports:
      - 50001:5001
    privileged: true
    tty: true
  earth_surface_1:
    build:
      context: .
      dockerfile: ./container-maker/Dockerfile
    container_name: earth_surface_1
    networks:
      test_net:
        ipv4_address: 192.168.10.149
    volumes:
      - ./ion-dtn-test/host149.rc:/dtn/host149.rc
    ports:
      - 50000:5001
    privileged: true
    tty: true
  moon_orbit_1:
    build:
      context: .
      dockerfile: ./container-maker/Dockerfile
    container_name: moon_orbit_1
    networks:
      test_net:
        ipv4_address: 192.168.10.151
    volumes:
      - ./ion-dtn-test/host149.rc:/dtn/host151.rc
    ports:
      - 50002:5001
    privileged: true
    tty: true
version: '3.7'
