#!/bin/bash
docker exec -it earth_surface_1 iptables -A FORWARD -i en0 -o en1 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en1 -o en0 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en0 -o en2 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en2 -o en0 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en0 -o en3 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en3 -o en0 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en0 -o en4 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en4 -o en0 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en0 -o en5 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en5 -o en0 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en1 -o en2 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en2 -o en1 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en1 -o en3 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en3 -o en1 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en1 -o en4 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en4 -o en1 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en1 -o en5 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en5 -o en1 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en2 -o en3 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en3 -o en2 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en2 -o en4 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en4 -o en2 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en2 -o en5 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en5 -o en2 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en3 -o en4 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en4 -o en3 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en3 -o en5 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en5 -o en3 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en4 -o en5 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en5 -o en4 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en0 -o en1 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en1 -o en0 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en0 -o en2 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en2 -o en0 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en0 -o en3 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en3 -o en0 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en0 -o en4 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en4 -o en0 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en0 -o en5 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en5 -o en0 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en1 -o en2 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en2 -o en1 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en1 -o en3 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en3 -o en1 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en1 -o en4 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en4 -o en1 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en1 -o en5 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en5 -o en1 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en2 -o en3 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en3 -o en2 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en2 -o en4 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en4 -o en2 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en2 -o en5 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en5 -o en2 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en3 -o en4 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en4 -o en3 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en3 -o en5 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en5 -o en3 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en4 -o en5 -j ACCEPT
docker exec -it earth_surface_2 iptables -A FORWARD -i en5 -o en4 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en0 -o en1 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en1 -o en0 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en0 -o en2 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en2 -o en0 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en0 -o en3 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en3 -o en0 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en0 -o en4 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en4 -o en0 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en0 -o en5 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en5 -o en0 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en1 -o en2 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en2 -o en1 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en1 -o en3 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en3 -o en1 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en1 -o en4 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en4 -o en1 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en1 -o en5 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en5 -o en1 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en2 -o en3 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en3 -o en2 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en2 -o en4 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en4 -o en2 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en2 -o en5 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en5 -o en2 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en3 -o en4 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en4 -o en3 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en3 -o en5 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en5 -o en3 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en4 -o en5 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en5 -o en4 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en0 -o en1 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en1 -o en0 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en0 -o en2 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en2 -o en0 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en0 -o en3 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en3 -o en0 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en0 -o en4 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en4 -o en0 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en0 -o en5 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en5 -o en0 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en1 -o en2 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en2 -o en1 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en1 -o en3 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en3 -o en1 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en1 -o en4 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en4 -o en1 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en1 -o en5 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en5 -o en1 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en2 -o en3 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en3 -o en2 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en2 -o en4 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en4 -o en2 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en2 -o en5 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en5 -o en2 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en3 -o en4 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en4 -o en3 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en3 -o en5 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en5 -o en3 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en4 -o en5 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en5 -o en4 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en0 -o en1 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en1 -o en0 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en0 -o en2 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en2 -o en0 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en0 -o en3 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en3 -o en0 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en0 -o en4 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en4 -o en0 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en0 -o en5 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en5 -o en0 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en1 -o en2 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en2 -o en1 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en1 -o en3 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en3 -o en1 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en1 -o en4 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en4 -o en1 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en1 -o en5 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en5 -o en1 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en2 -o en3 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en3 -o en2 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en2 -o en4 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en4 -o en2 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en2 -o en5 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en5 -o en2 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en3 -o en4 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en4 -o en3 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en3 -o en5 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en5 -o en3 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en4 -o en5 -j ACCEPT
docker exec -it moon_orbit_2 iptables -A FORWARD -i en5 -o en4 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en0 -o en1 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en1 -o en0 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en0 -o en2 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en2 -o en0 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en0 -o en3 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en3 -o en0 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en0 -o en4 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en4 -o en0 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en0 -o en5 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en5 -o en0 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en1 -o en2 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en2 -o en1 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en1 -o en3 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en3 -o en1 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en1 -o en4 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en4 -o en1 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en1 -o en5 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en5 -o en1 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en2 -o en3 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en3 -o en2 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en2 -o en4 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en4 -o en2 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en2 -o en5 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en5 -o en2 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en3 -o en4 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en4 -o en3 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en3 -o en5 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en5 -o en3 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en4 -o en5 -j ACCEPT
docker exec -it moon_surface_1 iptables -A FORWARD -i en5 -o en4 -j ACCEPT