#!/bin/bash
docker exec -it earth_surface_1 iptables -A FORWARD -i en0 -o en1 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en1 -o en0 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en0 -o en2 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en2 -o en0 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en1 -o en2 -j ACCEPT
docker exec -it earth_surface_1 iptables -A FORWARD -i en2 -o en1 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en0 -o en1 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en1 -o en0 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en0 -o en2 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en2 -o en0 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en1 -o en2 -j ACCEPT
docker exec -it earth_orbit_1 iptables -A FORWARD -i en2 -o en1 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en0 -o en1 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en1 -o en0 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en0 -o en2 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en2 -o en0 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en1 -o en2 -j ACCEPT
docker exec -it moon_orbit_1 iptables -A FORWARD -i en2 -o en1 -j ACCEPT